version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "academy22-gender-bias-prediction"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rz8436y9hm2b"
s3_prefix = "academy22-gender-bias-prediction"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["InferenceFunction=991775080983.dkr.ecr.eu-west-2.amazonaws.com/academy22-gender-bias-prediction-api"]
